debug oidc

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -39,7 +39,12 @@ jobs:
       - name: Build package
         run: poetry build
 
+      - name: Debug OIDC Token
+        run: |
+          curl -H "Authorization: Bearer $(jq -r '.id_token' $ACTIONS_ID_TOKEN_REQUEST_URL)" \
+          $ACTIONS_ID_TOKEN_REQUEST_URL || echo "Failed to fetch OIDC token"
+
       - name: Publish to PyPI using OpenID Connect
         env:
-          POETRY_PYPI_TOKEN_PYPI: __token__
+          POETRY_PYPI_TOKEN_PYPI: pypi
         run: poetry publish
